"""Apply only transcript-VERIFIED Listening artifacts to runtime datasets."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "project" / "data" / "tests"
CACHE_VERSION = "20260826-contract-v1"


def verification(artifact: dict) -> dict:
    evidence = {
        "contractVersion": 1,
        "sourceTranscriptSha256": artifact.get("sourceTranscriptSha256"),
        "audioSha256": artifact["sha256"],
        "transcriptEvidence": artifact["transcriptEvidence"],
        "fullTaskContentPresent": True,
        "openingMatched": True,
        "endingMatched": True,
        "noPreviousTaskContamination": True,
        "noNextTaskContamination": True,
        "recordingBoundaryVerified": True,
        "discardedIncompleteSourceRenditions": artifact.get("discardedIncompleteRenditions", 0),
    }
    if artifact.get("sourceMasterTestId"):
        evidence["sourceMasterTestId"] = artifact["sourceMasterTestId"]
    if artifact.get("sourceDuplicateRecovery"):
        evidence["sourceDuplicateRecovery"] = artifact["sourceDuplicateRecovery"]
    return evidence


def apply_audio(audio: dict, artifact: dict | None) -> None:
    audio.pop("start", None)
    audio.pop("end", None)
    if not artifact or artifact["status"] != "VERIFIED":
        audio["url"] = ""
        for key in ("sha256", "sourceClips", "cacheVersion", "duration"):
            audio.pop(key, None)
        # The forensic layer uses UNCERTAIN.  Runtime schemas expose the same
        # fail-closed state as NOT_VERIFIED and never provide a playable URL.
        audio["status"] = "NOT_VERIFIED"
        audio["audioSegmentStatus"] = "NOT_VERIFIED"
        audio["verification"] = {
            "contractVersion": 1,
            "recordingBoundaryVerified": False,
            "reason": (artifact or {}).get(
                "reason", "Generated bytes did not pass source transcript validation"
            ),
        }
        return
    audio.update(
        {
            "url": artifact["url"],
            "status": "VERIFIED",
            "audioSegmentStatus": "VERIFIED",
            "duration": round(artifact["durationSeconds"], 2),
            "sha256": artifact["sha256"],
            "sourceClips": artifact["masterClips"],
            "cacheVersion": CACHE_VERSION,
            "verification": verification(artifact),
        }
    )


def apply_test(result: dict) -> Path:
    test_id = result["audit"]["testId"]
    path = DATA_DIR / f"{test_id}-public.json"
    dataset = json.loads(path.read_text(encoding="utf-8"))
    artifacts = {artifact["blockId"]: artifact for artifact in result["artifacts"]}
    parts = dataset["listening"]["parts"]

    for index, task in enumerate(parts[0]["tasks"], start=1):
        artifact = artifacts.get(f"p1-q{index:02d}")
        apply_audio(task["audio"], artifact)
        task["audioUrl"] = task["audio"].get("url", task.get("audioUrl", ""))
    part1_verified = all(task["audio"]["status"] == "VERIFIED" for task in parts[0]["tasks"])
    parts[0]["audio"]["status"] = "VERIFIED" if part1_verified else "NOT_VERIFIED"

    apply_audio(parts[1]["audio"], artifacts.get("p2-task-all"))
    for letter, speaker in zip("abcd", parts[1]["speakers"]):
        apply_audio(speaker["audio"], artifacts.get(f"p2-spk-{letter}"))

    apply_audio(parts[2]["audio"], artifacts.get("p3-task-all"))
    for statement in parts[2]["statements"]:
        statement["audio"] = dict(parts[2]["audio"])

    apply_audio(parts[3]["audio"], artifacts.get("p4-task-all"))
    for index, monologue in enumerate(parts[3]["monologues"], start=1):
        apply_audio(monologue["audio"], artifacts.get(f"p4-mono{index}"))

    dataset["metadata"]["listeningContractVersion"] = 1
    dataset["metadata"]["listeningAudioCacheVersion"] = CACHE_VERSION
    path.write_text(json.dumps(dataset, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()
    manifest_path = args.manifest if args.manifest.is_absolute() else ROOT / args.manifest
    results = json.loads(manifest_path.read_text(encoding="utf-8"))
    for result in results:
        path = apply_test(result)
        print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
